development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: addressbook_dev
  pool: 5
  username: root
  password: password
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: addressbook_production
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock
